version: '2'

services:
  nats:
    # Build action should be successful from any RHEL Host system running the Docker service with subscription managed registered
    # + info: https://access.redhat.com/solutions/253273
    build: .
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
